# Generated by Django 2.1.5 on 2019-01-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_text',
            new_name='question',
        ),
    ]
