# Generated by Django 2.1.5 on 2019-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0006_auto_20190118_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=['%d/%m/%y']),
        ),
    ]
