# Generated by Django 2.1.5 on 2019-01-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0008_auto_20190119_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
