# Generated by Django 2.1.5 on 2019-01-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0011_auto_20190119_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
    ]
