# Generated by Django 2.1.5 on 2019-01-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0015_auto_20190119_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question_text',
        ),
    ]
